#language: none
#
#runtime:
#  # Allow cross platform builds
#  nodePool: shippable_shared_aarch64
#  #nodePool: default_node_pool
#
#env:
#  #- ca=--external-ca privileged=--privileged
#  - privileged=--privileged
#    #arch=$(lscpu | grep Arch | awk '{ print $2 }')
#
#build:
#
#  ci:
#    - arch: $(lscpu | grep Arch | awk '{ print $2 }')
#    - echo $arch
#    - sed -i 's|registry.fedoraproject.org/||' Dockerfile.fedora-27
#    - sed -i 's/^# debug:\s*//' Dockerfile.fedora-27
#    - docker build -t local/freeipa-server -f Dockerfile.fedora-27 .
#    - tests/run-master-and-replica.sh local/freeipa-server
#
#  post_ci:
#    - docker tag local/freeipa-server jmreicha/freeipa-server:arm64
#    - docker push jmreicha/freeipa-server:arm64
#
#integrations:
#	hub:
#		- integrationName: dockerhub
#			type: dockerRegistryLogin

templates: &build-test-push
  - cd IN/freeipa-container-gitRepo/gitRepo
  - sed -i 's|registry.fedoraproject.org/||' Dockerfile.fedora-27
  - sed -i 's/^# debug:\s*//' Dockerfile.fedora-27
  - docker build -t local/freeipa-server -f Dockerfile.fedora-27 .
  - tests/run-master-and-replica.sh local/freeipa-server
  - docker tag local/freeipa-server jmreicha/freeipa-server:$arch
  - docker push jmreicha/freeipa-server:$arch

resources:
    - name: freeipa-container-gitRepo
      type: gitRepo
      integration: freeipa-container-gitRepo
      versionTemplate:
          sourceName: jmreicha/freeipa-container
          branch: master

jobs:
  - name: build_amd64
    type: runSh
    runtime:
      nodePool: default_node_pool
      container: true
    steps:
      - IN: freeipa-container-gitRepo
      - IN: freeipa-container_master_rSync
      - TASK:
          runtime:
            options:
              env:
                - privileged: --privileged
                # Hardcode this for now
                # Also look at using SHIPPABLE_NODE_ARCHITECTURE
                - arch: amd64
          script:
            - *build-test-push

  - name: build_arm64
    type: runSh
    runtime:
      nodePool: shippable_shared_aarch64
      container: true
    steps:
      - IN: freeipa-container-gitRepo
      - IN: freeipa-container_master_rSync
      - TASK:
          runtime:
            options:
              env:
                - privileged: --privileged
                # Hardcode this for now
                - arch: arm64
          script:
            - *build-test-push

integrations:
	hub:
		- integrationName: dockerhub
			type: dockerRegistryLogin

