templates: &build-test-push
  - sed -i 's|registry.fedoraproject.org/||' Dockerfile.fedora-27
  - sed -i 's/^# debug:\s*//' Dockerfile.fedora-27
  - docker build -t local/freeipa-server -f Dockerfile.fedora-27 .
  - tests/run-master-and-replica.sh local/freeipa-server
  - docker tag local/freeipa-server jmreicha/freeipa-server:$arch
  - docker push jmreicha/freeipa-server:$arch

language: none

#runtime:
#  # Allow cross platform builds
#  nodePool: shippable_shared_aarch64
#  #nodePool: default_node_pool

env:
  #- ca=--external-ca privileged=--privileged
  - privileged=--privileged
    #arch=$(lscpu | grep Arch | awk '{ print $2 }')

jobs:
  - name: Build amd64
    type: runSh
    runtime: default_node_pool
    steps:
      - TASK:
          runtime:
            options:
              env:
                - arch=$(lscpu | grep Arch | awk '{ print $2 }')
          script:
            - *build-test-push

  - name: Build arm64
    type: runSh
    runtime: shippable_shared_aarch64
    steps:
      - TASK:
          runtime:
            options:
              env:
                - arch=$(lscpu | grep Arch | awk '{ print $2 }')
          script:
            - *build-test-push

#build:
#
#  ci:
#    - echo $arch
#    - sed -i 's|registry.fedoraproject.org/||' Dockerfile.fedora-27
#    - sed -i 's/^# debug:\s*//' Dockerfile.fedora-27
#    - docker build -t local/freeipa-server -f Dockerfile.fedora-27 .
#    - tests/run-master-and-replica.sh local/freeipa-server
#
#  post_ci:
#    - docker tag local/freeipa-server jmreicha/freeipa-server:arm64
#    - docker push jmreicha/freeipa-server:arm64

integrations:
  hub:
    - integrationName: dockerhub
      type: dockerRegistryLogin
